# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Decio < Formula
  desc "Typed decisions from context with optional command dispatch"
  homepage "https://github.com/youyo/decio"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/youyo/decio/releases/download/v0.1.0/decio_0.1.0_darwin_amd64.tar.gz"
      sha256 "0cda2790854da80e7df7bf97aaba0976c653b622f8b46971e43996e87b5e6aaf"

      def install
        bin.install "decio"
        generate_completions_from_executable(bin/"decio", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/youyo/decio/releases/download/v0.1.0/decio_0.1.0_darwin_arm64.tar.gz"
      sha256 "74937fdd358a4512989e234131df7a0c9015c9080d7aeb4c41137b3159f1f498"

      def install
        bin.install "decio"
        generate_completions_from_executable(bin/"decio", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/decio/releases/download/v0.1.0/decio_0.1.0_linux_amd64.tar.gz"
      sha256 "632a86815211bdd7e03ad11a7687a9734e0a796f961332ba103476310542b0a2"
      def install
        bin.install "decio"
        generate_completions_from_executable(bin/"decio", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/decio/releases/download/v0.1.0/decio_0.1.0_linux_arm64.tar.gz"
      sha256 "cc2d30470c01ce1c20d7912c58b36613d6a3abf98e5f4be216011cc9bb47f459"
      def install
        bin.install "decio"
        generate_completions_from_executable(bin/"decio", "completion")
      end
    end
  end
end
