# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kintone < Formula
  desc "kintone CLI / MCP server"
  homepage "https://github.com/youyo/kintone"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/youyo/kintone/releases/download/v0.2.0/kintone_0.2.0_Darwin_x86_64.tar.gz"
      sha256 "f34d2712120e7297f812a34cedf7aa1c5cde418c1677cbb2c3c8fe563afd1605"

      define_method(:install) do
        bin.install "kintone"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/youyo/kintone/releases/download/v0.2.0/kintone_0.2.0_Darwin_arm64.tar.gz"
      sha256 "85e586a982be3be849e9803bd0f8c37eacb3cfb8d299cc8adc67db332cfe9922"

      define_method(:install) do
        bin.install "kintone"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/kintone/releases/download/v0.2.0/kintone_0.2.0_Linux_x86_64.tar.gz"
      sha256 "3ac22ca0de5078bff0569800a67c8286b2d06ce0b5cdcacd333401e7dd7ca86c"
      define_method(:install) do
        bin.install "kintone"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/kintone/releases/download/v0.2.0/kintone_0.2.0_Linux_arm64.tar.gz"
      sha256 "82640e4c285738989ed88bc405e9d07ea1d8785cc466f4c33c7fc87ff5ad0f62"
      define_method(:install) do
        bin.install "kintone"
      end
    end
  end

  test do
    system "#{bin}/kintone version"
  end
end
