# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Memoria < Formula
  desc "Claude Code 向けプロジェクト認識型ローカル RAG メモリシステム"
  homepage "https://github.com/youyo/memoria"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/youyo/memoria/releases/download/v0.1.0/memoria_0.1.0_darwin_amd64.tar.gz"
      sha256 "3c931b4d202710e129454f8b329d54b361965a6e90771823e9337f5962632e72"

      define_method(:install) do
        bin.install "memoria"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/youyo/memoria/releases/download/v0.1.0/memoria_0.1.0_darwin_arm64.tar.gz"
      sha256 "585d5a7cd3889f572a61e29338a39a9fde32ff2ad01c43e8e91a03ed5d015770"

      define_method(:install) do
        bin.install "memoria"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/memoria/releases/download/v0.1.0/memoria_0.1.0_linux_amd64.tar.gz"
      sha256 "c2edc3febd24ea22f0f3a4ff9089f1682c420500ec7cfca6ec9316b1047e24c9"
      define_method(:install) do
        bin.install "memoria"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/memoria/releases/download/v0.1.0/memoria_0.1.0_linux_arm64.tar.gz"
      sha256 "560b913701e260843d787cc92063b8e75c4596dd44e7b3ebcf71bc6f9e3bcf7d"
      define_method(:install) do
        bin.install "memoria"
      end
    end
  end

  test do
    system "#{bin}/memoria version"
  end
end
