# This file was generated by GoReleaser. DO NOT EDIT.
cask "passgen" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/youyo/passgen/releases/download/v#{version}/passgen_#{version}_darwin_amd64.zip"
      sha256 "49c47112aecdbd552638ba786657ecf88845d0bfd3e6dc9643c85f1d9c4b9c7a"
    end
    on_arm do
      url "https://github.com/youyo/passgen/releases/download/v#{version}/passgen_#{version}_darwin_arm64.zip"
      sha256 "aa676cf5a16818ecd119f03e1f3355efdda6397261cd99773914f9a7d1a2fa94"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/youyo/passgen/releases/download/v#{version}/passgen_#{version}_linux_amd64.tar.gz"
      sha256 "d3e218fb5e914b727e0841aee08ce3fd64b986bd728b0ad89af3d3c1bc1900d0"
    end
  end

  name "passgen"
  desc "Simple and secure password generator CLI tool"
  homepage "https://github.com/youyo/passgen"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "passgen"

  # No zap stanza required

end
