# This file was generated by GoReleaser. DO NOT EDIT.
class Awscredswrap < Formula
  desc "awscredswrap uses temporary credentials for the specified iam role to set a shell environment variable or execute a command."
  homepage "https://github.com/youyo/awscredswrap"
  version "1.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/youyo/awscredswrap/releases/download/v1.0.1/awscredswrap_1.0.1_Darwin_x86_64.tar.gz"
    sha256 "048b4d805f228f039c17b74668c2ce4cde328b134853551b25b0802a07f8ae59"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/youyo/awscredswrap/releases/download/v1.0.1/awscredswrap_1.0.1_Linux_x86_64.tar.gz"
      sha256 "9eba5dcdc0e2cf4bfb7d6cfa86ec7d3c1f8749ad4ddc45f27da8b360d5ceb706"
    end
  end

  def install
    bin.install "awscredswrap"
    zsh_completion.install '_awscredswrap'
  end

  test do
    system "#{bin}/awscredswrap --version"
  end
end
