# This file was generated by GoReleaser. DO NOT EDIT.
class Awscredswrap < Formula
  desc "awscredswrap uses temporary credentials for the specified iam role to set a shell environment variable or execute a command."
  homepage "https://github.com/youyo/awscredswrap"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/youyo/awscredswrap/releases/download/v1.0.0/awscredswrap_1.0.0_Darwin_x86_64.tar.gz"
    sha256 "7964adb0f7a36aff6321beeb8388350375caaf40bbe06f7faeb9b4cd0c6fd27d"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/youyo/awscredswrap/releases/download/v1.0.0/awscredswrap_1.0.0_Linux_x86_64.tar.gz"
      sha256 "a60de6f3a6cc157e07e66dc912b45405199b2073a2e7de7d73876a6b196b1ec2"
    end
  end

  def install
    bin.install "awscredswrap"
    zsh_completion.install '_awscredswrap'
  end

  test do
    system "#{bin}/awscredswrap --version"
  end
end
