# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awslogin < Formula
  desc "Generate AWS Management Console login URL"
  homepage "https://github.com/youyo/awslogin"
  version "3.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/youyo/awslogin/releases/download/v3.1.2/awslogin_3.1.2_darwin_amd64.tar.gz"
      sha256 "fe1f1cbf7320f7948e0ed6714df353ed47dd2b3c3e751180588b79ac97419bdc"

      define_method(:install) do
        bin.install "awslogin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/youyo/awslogin/releases/download/v3.1.2/awslogin_3.1.2_darwin_arm64.tar.gz"
      sha256 "4ea351cd29f2ac95263160d1fe20a67f8f82bd3aec71c3eee7a37ff01b7b83bc"

      define_method(:install) do
        bin.install "awslogin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/awslogin/releases/download/v3.1.2/awslogin_3.1.2_linux_amd64.tar.gz"
      sha256 "880b3048f57be2c7d511b14393410cc583c960c4905b86b000085ce4359b4138"
      define_method(:install) do
        bin.install "awslogin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/awslogin/releases/download/v3.1.2/awslogin_3.1.2_linux_arm64.tar.gz"
      sha256 "354bf110950768c458b79c108431d677d6139e14b69d6c77bd9e72b459ba69c8"
      define_method(:install) do
        bin.install "awslogin"
      end
    end
  end

  test do
    system "#{bin}/awslogin", "version"
  end
end
