# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awslogin < Formula
  desc "Generate AWS Management Console login URL"
  homepage "https://github.com/youyo/awslogin"
  version "3.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/youyo/awslogin/releases/download/v3.0.0/awslogin_3.0.0_darwin_amd64.tar.gz"
      sha256 "32afabab0a7c5db4bdd62bb8dbce2cee8bf7d0d909f8feace1535253ec800596"

      define_method(:install) do
        bin.install "awslogin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/youyo/awslogin/releases/download/v3.0.0/awslogin_3.0.0_darwin_arm64.tar.gz"
      sha256 "f75631bf2feb14de787d23d070138cb7f2d7408b6699cda425847ba56d1fac18"

      define_method(:install) do
        bin.install "awslogin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/awslogin/releases/download/v3.0.0/awslogin_3.0.0_linux_amd64.tar.gz"
      sha256 "0021b966e0cc5000720564b952195f7bbf510e3b388cacc3cc5109af4445c661"
      define_method(:install) do
        bin.install "awslogin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/awslogin/releases/download/v3.0.0/awslogin_3.0.0_linux_arm64.tar.gz"
      sha256 "00604c7bb40bc3b607e3f76a305d8dbaa93a0aadd1ccb0789d7ee57e60ee052a"
      define_method(:install) do
        bin.install "awslogin"
      end
    end
  end

  test do
    system "#{bin}/awslogin", "version"
  end
end
