# This file was generated by GoReleaser. DO NOT EDIT.
class Awslogin < Formula
  desc "Login to the AWS management console."
  homepage "https://github.com/youyo/awslogin"
  version "2.0.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/youyo/awslogin/releases/download/v2.0.5/awslogin_2.0.5_Darwin_x86_64.tar.gz"
    sha256 "309738f151404901148df92740a39b6b6b2a92b23b52a0bd0f3702edbe76cfc4"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/youyo/awslogin/releases/download/v2.0.5/awslogin_2.0.5_Linux_x86_64.tar.gz"
      sha256 "57903c41df18b30b2d435e1bf167d5baf85077dff43189311da1c3a5cc3e9a41"
    end
  end

  def install
    bin.install "awslogin"
    zsh_completion.install '_awslogin'
  end

  test do
    system "#{bin}/awslogin --version"
  end
end
