# This file was generated by GoReleaser. DO NOT EDIT.
class Awssh < Formula
  desc "CLI tool to login ec2 instance"
  homepage "https://github.com/youyo/awssh"
  version "0.2.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/youyo/awssh/releases/download/v0.2.5/awssh_0.2.5_Darwin_x86_64.tar.gz"
    sha256 "68b538f1a4cd754dd63f0be6959722691fae1f9fb4b4fa2a909e521e0574a902"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/youyo/awssh/releases/download/v0.2.5/awssh_0.2.5_Linux_x86_64.tar.gz"
      sha256 "6ec7153c71374bd761f8eeee6a82e985a876eea76eafe522d52e96fb73e49292"
    end
  end

  def install
    bin.install "awssh"
    output = Utils.popen_read("#{bin}/awssh --completion-zsh")
    (zsh_completion/"_awssh").write output
  end

  test do
    system "#{bin}/awssh --version"
  end
end
