# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Board < Formula
  desc "BOARD API CLI + local MCP server"
  homepage "https://github.com/youyo/board"
  version "0.10.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/youyo/board/releases/download/v0.10.0/board_0.10.0_Darwin_x86_64.tar.gz"
      sha256 "27bc4f9b7c681ec441e136a732f9a1e7be129e910770f5e813655b5b8781b3b8"

      define_method(:install) do
        bin.install "board"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/youyo/board/releases/download/v0.10.0/board_0.10.0_Darwin_arm64.tar.gz"
      sha256 "e45b62b00a4b343812758f937b118fe9db792ca3012fb777e7fc23e2925c0b82"

      define_method(:install) do
        bin.install "board"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/board/releases/download/v0.10.0/board_0.10.0_Linux_x86_64.tar.gz"
      sha256 "78be2376f3239981108c4cb9ee90fec00f2d387b4ca1a2723175b03a256465dc"
      define_method(:install) do
        bin.install "board"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/board/releases/download/v0.10.0/board_0.10.0_Linux_arm64.tar.gz"
      sha256 "1ef34808feaf51c699a4dfe0aab31caee4335589a25fdcfae4f6a138da08fc02"
      define_method(:install) do
        bin.install "board"
      end
    end
  end

  test do
    system "#{bin}/board", "--help"
  end
end
