# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Board < Formula
  desc "BOARD API CLI + local MCP server"
  homepage "https://github.com/youyo/board"
  version "0.11.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/youyo/board/releases/download/v0.11.1/board_0.11.1_Darwin_x86_64.tar.gz"
      sha256 "319244753997b50e9f0b6e4d6929cc51a91aa70a1ca74fb7025b4dc22028cb0c"

      define_method(:install) do
        bin.install "board"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/youyo/board/releases/download/v0.11.1/board_0.11.1_Darwin_arm64.tar.gz"
      sha256 "ee84dfa58bc6265e3052847d791ad7940339207f763991728b4afbbfd125ff2c"

      define_method(:install) do
        bin.install "board"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/board/releases/download/v0.11.1/board_0.11.1_Linux_x86_64.tar.gz"
      sha256 "46715db1bee2b857f7d2aa701de6b30b2b76368961cb542cc83cf68a5bfebc00"
      define_method(:install) do
        bin.install "board"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/board/releases/download/v0.11.1/board_0.11.1_Linux_arm64.tar.gz"
      sha256 "8e5e500ff8c5c30af68ddd441b7276154d3cd1efbb96a2ca485db484358b18b9"
      define_method(:install) do
        bin.install "board"
      end
    end
  end

  test do
    system "#{bin}/board", "--help"
  end
end
