# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Board < Formula
  desc "BOARD API CLI + local MCP server"
  homepage "https://github.com/youyo/board"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/youyo/board/releases/download/v0.1.1/board_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "c6d4186042b7036078cd0b15649142a15d35ee724efe47b279790966f26cb339"

      define_method(:install) do
        bin.install "board"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/youyo/board/releases/download/v0.1.1/board_0.1.1_Darwin_arm64.tar.gz"
      sha256 "2d9be4fb690b53589bc078ae45b6e5c719cd73ea15aa80fb6f1c3fcab42ae3b4"

      define_method(:install) do
        bin.install "board"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/board/releases/download/v0.1.1/board_0.1.1_Linux_x86_64.tar.gz"
      sha256 "d0ecd982fef04317a9c9760dbc4b7307e7dfe0d3a15e01999a1b5a4a21812a72"
      define_method(:install) do
        bin.install "board"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/board/releases/download/v0.1.1/board_0.1.1_Linux_arm64.tar.gz"
      sha256 "c560f6bf717a457699cd6c23ddbea23214ddb16eb73ffd9dfa04e8ed8de88e09"
      define_method(:install) do
        bin.install "board"
      end
    end
  end

  test do
    system "#{bin}/board", "--help"
  end
end
