# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bundr < Formula
  desc "AWS Parameter Store と Secrets Manager を統合する単一バイナリ Go CLI"
  homepage "https://github.com/youyo/bundr"
  version "0.4.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/youyo/bundr/releases/download/v0.4.6/bundr_0.4.6_darwin_amd64.tar.gz"
      sha256 "f59ee34366e2d33e615dc8d63f80224fcd82228bf36912f84e0f2ec5304f8bac"

      define_method(:install) do
        bin.install "bundr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/youyo/bundr/releases/download/v0.4.6/bundr_0.4.6_darwin_arm64.tar.gz"
      sha256 "9dad098e1de0fb964472c6ea5206f301330ebc6618ce33cc49f4a31f4751c0fa"

      define_method(:install) do
        bin.install "bundr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/bundr/releases/download/v0.4.6/bundr_0.4.6_linux_amd64.tar.gz"
      sha256 "aab2c8a8a70cca3964c11d9b29617505a2a92997db8b9086f1d6aba5d163b0f0"
      define_method(:install) do
        bin.install "bundr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/bundr/releases/download/v0.4.6/bundr_0.4.6_linux_arm64.tar.gz"
      sha256 "537d584c852cce2772776068cbb2bcf63446eb4203518ac2d341cfd0287ffde1"
      define_method(:install) do
        bin.install "bundr"
      end
    end
  end

  test do
    system "#{bin}/bundr", "--help"
  end
end
