# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bundr < Formula
  desc "AWS Parameter Store と Secrets Manager を統合する単一バイナリ Go CLI"
  homepage "https://github.com/youyo/bundr"
  version "0.6.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/youyo/bundr/releases/download/v0.6.1/bundr_0.6.1_darwin_amd64.tar.gz"
      sha256 "2683444d10f4660380ddb7976bef7d095358ebf3df7064337925cc5cf8914cb6"

      define_method(:install) do
        bin.install "bundr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/youyo/bundr/releases/download/v0.6.1/bundr_0.6.1_darwin_arm64.tar.gz"
      sha256 "386dce7604077326e7aca8fb6cb2cf63240cde94ea21fd037a3a82914f6e1d01"

      define_method(:install) do
        bin.install "bundr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/bundr/releases/download/v0.6.1/bundr_0.6.1_linux_amd64.tar.gz"
      sha256 "d5db41e34e39a66dd3d9b8938adc0dab6fabd014b4a1abe7e08d522535ca37d9"
      define_method(:install) do
        bin.install "bundr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/bundr/releases/download/v0.6.1/bundr_0.6.1_linux_arm64.tar.gz"
      sha256 "a63acd8282b3fea953787058fbdbeea693bb0326aa786a8f9f7e04b717aaa4eb"
      define_method(:install) do
        bin.install "bundr"
      end
    end
  end

  test do
    system "#{bin}/bundr", "--help"
  end
end
