# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccmix < Formula
  desc "Claude Code settings mixer - TUI/CLI for managing settings across scopes"
  homepage "https://github.com/youyo/ccmix"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/youyo/ccmix/releases/download/v0.1.1/ccmix_0.1.1_darwin_amd64.tar.gz"
      sha256 "c2b94d46243d6c8dfa576fb0e6caff0791e16dcc88e494dbade6802f834c1d4f"

      define_method(:install) do
        bin.install "ccmix"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/youyo/ccmix/releases/download/v0.1.1/ccmix_0.1.1_darwin_arm64.tar.gz"
      sha256 "b3ee22317f5825f99970f7b6b5eecb02a056d2b2a8f432c50157c2d745d23138"

      define_method(:install) do
        bin.install "ccmix"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/ccmix/releases/download/v0.1.1/ccmix_0.1.1_linux_amd64.tar.gz"
      sha256 "9c1b47fac4df51ea528fb740fdd83dd384aa6bae0ca1d4da7042b1b3486c9f37"
      define_method(:install) do
        bin.install "ccmix"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/ccmix/releases/download/v0.1.1/ccmix_0.1.1_linux_arm64.tar.gz"
      sha256 "7efa95beffe716713f731d5f6f3365f5589482febebbb2019ea2b2dc98036961"
      define_method(:install) do
        bin.install "ccmix"
      end
    end
  end

  test do
    system "#{bin}/ccmix", "--help"
  end
end
