# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Decio < Formula
  desc "Typed decisions from context with optional command dispatch"
  homepage "https://github.com/youyo/decio"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/youyo/decio/releases/download/v0.1.1/decio_0.1.1_darwin_amd64.tar.gz"
      sha256 "761d27df56af0d8e6fa9014e8a5b6e36fd0ad2545ed49e3aaaec1feb221f9fc6"

      def install
        bin.install "decio"
        generate_completions_from_executable(bin/"decio", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/youyo/decio/releases/download/v0.1.1/decio_0.1.1_darwin_arm64.tar.gz"
      sha256 "b907a02dd354ff8ba25b6b23c7a45c33ce579655a08faae0a85bdd8fbef00fa5"

      def install
        bin.install "decio"
        generate_completions_from_executable(bin/"decio", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/decio/releases/download/v0.1.1/decio_0.1.1_linux_amd64.tar.gz"
      sha256 "fd57aa25a2195a5c7e36492abc684c8e7d6a0f6e6d9873295b4c2567058e6ed2"
      def install
        bin.install "decio"
        generate_completions_from_executable(bin/"decio", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/decio/releases/download/v0.1.1/decio_0.1.1_linux_arm64.tar.gz"
      sha256 "65911064b14bfa2f56b43e8ec20c45e8677f87dc9086ec8f273cad8ac94784d9"
      def install
        bin.install "decio"
        generate_completions_from_executable(bin/"decio", "completion")
      end
    end
  end
end
