# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Decio < Formula
  desc "Typed decisions from context with optional command dispatch"
  homepage "https://github.com/youyo/decio"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/youyo/decio/releases/download/v0.3.0/decio_0.3.0_darwin_amd64.tar.gz"
      sha256 "5854b146d28b2a6f6c3d27803a7a7be4aded260cb011f421047f19f79bc34792"

      def install
        bin.install "decio"
        generate_completions_from_executable(bin/"decio", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/youyo/decio/releases/download/v0.3.0/decio_0.3.0_darwin_arm64.tar.gz"
      sha256 "89166c0b5448af5c3edf2061252d340b9f840b488dd166f1d086864be81f58fa"

      def install
        bin.install "decio"
        generate_completions_from_executable(bin/"decio", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/decio/releases/download/v0.3.0/decio_0.3.0_linux_amd64.tar.gz"
      sha256 "f5dc504b5de036930771bb533e63066e3171b0bd21aed1a9c91806fcb0e35766"
      def install
        bin.install "decio"
        generate_completions_from_executable(bin/"decio", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/decio/releases/download/v0.3.0/decio_0.3.0_linux_arm64.tar.gz"
      sha256 "b2ad34e2977736678b445c49cc71d00da052584ef8174a7453afaeddaf2ced98"
      def install
        bin.install "decio"
        generate_completions_from_executable(bin/"decio", "completion")
      end
    end
  end
end
