# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Focal < Formula
  desc "Give coding agents visibility, not shell access — restricted SSH inspection CLI + remote MCP"
  homepage "https://github.com/youyo/focal"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/youyo/focal/releases/download/v0.2.0/focal_0.2.0_Darwin_x86_64.tar.gz"
      sha256 "dbde8ef6862d062e5844edc536d0e958071e2b5f812b3bae4085d7ffd1854e7c"

      define_method(:install) do
        bin.install "focal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/youyo/focal/releases/download/v0.2.0/focal_0.2.0_Darwin_arm64.tar.gz"
      sha256 "68e3a5871a6a9dfe0e397822f1846cb7a6a01c5068536dd8110d955a01769cc3"

      define_method(:install) do
        bin.install "focal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/focal/releases/download/v0.2.0/focal_0.2.0_Linux_x86_64.tar.gz"
      sha256 "b39975c94ccd3115a1fa02f6d65cd1be170555bc4de0d4243f10382efc7f3f97"
      define_method(:install) do
        bin.install "focal"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/focal/releases/download/v0.2.0/focal_0.2.0_Linux_arm64.tar.gz"
      sha256 "352dbf26fd3ebfc5d6af54a32ba321d2ed1b3483acc02ac439242b0439f9b4f1"
      define_method(:install) do
        bin.install "focal"
      end
    end
  end

  test do
    system "#{bin}/focal", "--version"
  end
end
