# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Focal < Formula
  desc "Give coding agents visibility, not shell access — restricted SSH inspection CLI + remote MCP"
  homepage "https://github.com/youyo/focal"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/youyo/focal/releases/download/v0.2.1/focal_0.2.1_Darwin_x86_64.tar.gz"
      sha256 "3cd90e3de3ac931e921cf9e7e8310a4d516489d52e8cac3cd548f1e7afe9150c"

      define_method(:install) do
        bin.install "focal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/youyo/focal/releases/download/v0.2.1/focal_0.2.1_Darwin_arm64.tar.gz"
      sha256 "f482fef01806581a81cf9333154d9944da4ed7bc206df3cc14b7d66af2805807"

      define_method(:install) do
        bin.install "focal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/focal/releases/download/v0.2.1/focal_0.2.1_Linux_x86_64.tar.gz"
      sha256 "3b35eccae8af4f8c8c9933c7fc536b0cb380048cd27826d5219baebb0dc03dd7"
      define_method(:install) do
        bin.install "focal"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/focal/releases/download/v0.2.1/focal_0.2.1_Linux_arm64.tar.gz"
      sha256 "2a2f1f9a1502c120c83de8beb21ec5b7176dfc5c5d8d833a27e9e841add95378"
      define_method(:install) do
        bin.install "focal"
      end
    end
  end

  test do
    system "#{bin}/focal", "--version"
  end
end
