# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gform < Formula
  desc "IaC-style CLI for managing Google Forms (init / diff / apply / pull)"
  homepage "https://github.com/youyo/gform"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/youyo/gform/releases/download/v0.1.0/gform_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "40059dffd21428fa684740e137357886a0d4b266e98df63f65b3ec24087ab500"

      define_method(:install) do
        bin.install "gform"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/youyo/gform/releases/download/v0.1.0/gform_0.1.0_Darwin_arm64.tar.gz"
      sha256 "a3af1051f69098a554ed10187100619d611fca73c92ebd58a00ae0f52b39bf5b"

      define_method(:install) do
        bin.install "gform"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/gform/releases/download/v0.1.0/gform_0.1.0_Linux_x86_64.tar.gz"
      sha256 "fba9a7f92c4bc791608f2c668ec53298e9b890fe8908d6f7fbcfc22a550316eb"
      define_method(:install) do
        bin.install "gform"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/gform/releases/download/v0.1.0/gform_0.1.0_Linux_arm64.tar.gz"
      sha256 "1ea71a098180df06e0710d4c749e6f58147f18f9ad42265c4e1829530a460a5e"
      define_method(:install) do
        bin.install "gform"
      end
    end
  end

  test do
    system "#{bin}/gform", "--help"
  end
end
