# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Idproxy < Formula
  desc "idproxy - Identity-aware reverse proxy with OAuth 2.1"
  homepage "https://github.com/youyo/idproxy"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/youyo/idproxy/releases/download/v0.3.1/idproxy_0.3.1_darwin_amd64.tar.gz"
      sha256 "6a842bdad424e8e8d6f6b66950ff2590c1b0012eb4216429306007dbb60bb7a0"

      define_method(:install) do
        bin.install "idproxy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/youyo/idproxy/releases/download/v0.3.1/idproxy_0.3.1_darwin_arm64.tar.gz"
      sha256 "621aa3f6ccda7799ef0047167e150a1e8d284e396442d5a4e9d9645e8383ea66"

      define_method(:install) do
        bin.install "idproxy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/idproxy/releases/download/v0.3.1/idproxy_0.3.1_linux_amd64.tar.gz"
      sha256 "2cde480a65dccbf01a0aabf778f35c2e82edd632ed6e3f3be5cbe500e47dcd70"
      define_method(:install) do
        bin.install "idproxy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/idproxy/releases/download/v0.3.1/idproxy_0.3.1_linux_arm64.tar.gz"
      sha256 "434f61d390a1132748a87943fc518c518fed135b047d53262b84a9e1444ef424"
      define_method(:install) do
        bin.install "idproxy"
      end
    end
  end

  test do
    system "#{bin}/idproxy", "--help"
  end
end
