# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Idproxy < Formula
  desc "idproxy - Identity-aware reverse proxy with OAuth 2.1"
  homepage "https://github.com/youyo/idproxy"
  version "0.10.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/youyo/idproxy/releases/download/v0.10.2/idproxy_0.10.2_darwin_amd64.tar.gz"
      sha256 "9e0acb05a24f0d6f02c22f6ee3609eeeb1c7eaa1aa4c1132ce3dcf0cec028894"

      define_method(:install) do
        bin.install "idproxy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/youyo/idproxy/releases/download/v0.10.2/idproxy_0.10.2_darwin_arm64.tar.gz"
      sha256 "2dea7eea0efc2afb5f89728a7fc171a29e2c6638f1e79b15fbd1009315857570"

      define_method(:install) do
        bin.install "idproxy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/idproxy/releases/download/v0.10.2/idproxy_0.10.2_linux_amd64.tar.gz"
      sha256 "4d97f2c130e1e07197dc1326def6be988c32a99e11dce5eb56697c7e6eb2aae0"
      define_method(:install) do
        bin.install "idproxy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/idproxy/releases/download/v0.10.2/idproxy_0.10.2_linux_arm64.tar.gz"
      sha256 "fd3ab12bbef7e1d5fad2f245e7c25da74d47cf7438a21993f3d0a4daba0023e0"
      define_method(:install) do
        bin.install "idproxy"
      end
    end
  end

  test do
    system "#{bin}/idproxy", "--help"
  end
end
