# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Imgraft < Formula
  desc "Transparent image asset generator for LLM coding agents"
  homepage "https://github.com/youyo/imgraft"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/youyo/imgraft/releases/download/v0.1.2/imgraft_darwin_x86_64.zip"
      sha256 "fd176d853384369ac816033538b6a89ffb127f5b799577a19ed21f4fa5dfa886"

      define_method(:install) do
        bin.install "imgraft"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/youyo/imgraft/releases/download/v0.1.2/imgraft_darwin_arm64.zip"
      sha256 "4bd9faf0a18d0ea296bd55a9a74bc95a96d3ac63ca4deb7d052469da2c749821"

      define_method(:install) do
        bin.install "imgraft"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/imgraft/releases/download/v0.1.2/imgraft_linux_x86_64.tar.gz"
      sha256 "b26a76713a29f53856f831df72ab8c44191c1557913cfe22414f71552c529c29"
      define_method(:install) do
        bin.install "imgraft"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/imgraft/releases/download/v0.1.2/imgraft_linux_arm64.tar.gz"
      sha256 "669bab559e703906702afa8087cbbe075f6f13050205c87b9aa6d617eb16af78"
      define_method(:install) do
        bin.install "imgraft"
      end
    end
  end

  test do
    system "#{bin}/imgraft", "version"
  end
end
