# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Imgraft < Formula
  desc "Transparent image asset generator for LLM coding agents"
  homepage "https://github.com/youyo/imgraft"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/youyo/imgraft/releases/download/v0.1.0/imgraft_darwin_x86_64.zip"
      sha256 "ce7c31282f7d2e0e935ccc21bc4ed660ed3ce456816d205ef05bf76827371534"

      define_method(:install) do
        bin.install "imgraft"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/youyo/imgraft/releases/download/v0.1.0/imgraft_darwin_arm64.zip"
      sha256 "b13bb11829d7d4b8630267d94d1525cc08c4d6a48768b22f4ba74f05a59cf3fd"

      define_method(:install) do
        bin.install "imgraft"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/imgraft/releases/download/v0.1.0/imgraft_linux_x86_64.tar.gz"
      sha256 "8e8bb7c728fd0b058739523dbe7e9b225bab22ddf4360c84f0525f3b4ae63d00"
      define_method(:install) do
        bin.install "imgraft"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/imgraft/releases/download/v0.1.0/imgraft_linux_arm64.tar.gz"
      sha256 "e7f382d61cef8421a86c4a0f6061cba8de87dec3ad082a26c3a6d2f6f817b1cb"
      define_method(:install) do
        bin.install "imgraft"
      end
    end
  end

  test do
    system "#{bin}/imgraft", "version"
  end
end
