# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kintone < Formula
  desc "kintone CLI / MCP server"
  homepage "https://github.com/youyo/kintone"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/youyo/kintone/releases/download/v0.3.0/kintone_0.3.0_Darwin_x86_64.tar.gz"
      sha256 "b1265875786d337380b84a5e916366824882befbb0e0bfbe0bda6f2599049227"

      define_method(:install) do
        bin.install "kintone"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/youyo/kintone/releases/download/v0.3.0/kintone_0.3.0_Darwin_arm64.tar.gz"
      sha256 "b4ba0bf5e4d569dd48e8cb23e730779245e090c0602210ff16d97cdc48bc1676"

      define_method(:install) do
        bin.install "kintone"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/kintone/releases/download/v0.3.0/kintone_0.3.0_Linux_x86_64.tar.gz"
      sha256 "1672112ac3e3a35437bd59a9877dc932255827530c14ddabdddc065c30c859c2"
      define_method(:install) do
        bin.install "kintone"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/kintone/releases/download/v0.3.0/kintone_0.3.0_Linux_arm64.tar.gz"
      sha256 "25e1b1533a3fb03bad3c6d40a69b1343da792641dfc005d5390b47ad93a112bb"
      define_method(:install) do
        bin.install "kintone"
      end
    end
  end

  test do
    system "#{bin}/kintone version"
  end
end
