# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kintone < Formula
  desc "kintone CLI / MCP server"
  homepage "https://github.com/youyo/kintone"
  version "0.4.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/youyo/kintone/releases/download/v0.4.2/kintone_0.4.2_Darwin_x86_64.tar.gz"
      sha256 "178c0d79d655896614641c35e257fec238500f8af56344eb30ced0141081eaf9"

      define_method(:install) do
        bin.install "kintone"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/youyo/kintone/releases/download/v0.4.2/kintone_0.4.2_Darwin_arm64.tar.gz"
      sha256 "8c0e4e744a0bf01c45dbdff5f430a6829e6500fc032f94540360c1a523a7a9bf"

      define_method(:install) do
        bin.install "kintone"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/kintone/releases/download/v0.4.2/kintone_0.4.2_Linux_x86_64.tar.gz"
      sha256 "027db40ff2f1cc5e6a6c98591ea7d93a029e659f47704794a92979726749908a"
      define_method(:install) do
        bin.install "kintone"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/kintone/releases/download/v0.4.2/kintone_0.4.2_Linux_arm64.tar.gz"
      sha256 "80546495df08df48dacc672e0e37801f055d177defc0bafc9aa7115e90ad203f"
      define_method(:install) do
        bin.install "kintone"
      end
    end
  end

  test do
    system "#{bin}/kintone version"
  end
end
