# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kintone < Formula
  desc "kintone CLI / MCP server"
  homepage "https://github.com/youyo/kintone"
  version "0.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/youyo/kintone/releases/download/v0.5.1/kintone_0.5.1_Darwin_x86_64.tar.gz"
      sha256 "a2819f2d004cdd557d68677d33ef1ea527fbb582a8e36389e76b0c0cc4aad033"

      define_method(:install) do
        bin.install "kintone"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/youyo/kintone/releases/download/v0.5.1/kintone_0.5.1_Darwin_arm64.tar.gz"
      sha256 "0fd8d6a4fb5ac7c370e0d5c52c1450c4264fab226af200c3c483454909ee0bff"

      define_method(:install) do
        bin.install "kintone"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/kintone/releases/download/v0.5.1/kintone_0.5.1_Linux_x86_64.tar.gz"
      sha256 "b83dabda2d99c7a629f8717e38e226d9dd027c2f7f26c23d52ebf807295ca3f5"
      define_method(:install) do
        bin.install "kintone"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/kintone/releases/download/v0.5.1/kintone_0.5.1_Linux_arm64.tar.gz"
      sha256 "d941b6aad64c594574128803fde05b15656c60ed7cc01102b111b4fc2c46b013"
      define_method(:install) do
        bin.install "kintone"
      end
    end
  end

  test do
    system "#{bin}/kintone version"
  end
end
