# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Logvalet < Formula
  desc "LLM-first Backlog CLI with digest-oriented output"
  homepage "https://github.com/youyo/logvalet"
  version "0.19.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/youyo/logvalet/releases/download/v0.19.0/logvalet_0.19.0_Darwin_x86_64.tar.gz"
      sha256 "37e35008f797fd9f6d6ca8d01793d0463d657a6a1f08a206ed709bf7023ac595"

      define_method(:install) do
        bin.install "logvalet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/youyo/logvalet/releases/download/v0.19.0/logvalet_0.19.0_Darwin_arm64.tar.gz"
      sha256 "d93933e8b66b71cd2425a8ab879fe4930adc35803649c8ffa3ba69260808eacc"

      define_method(:install) do
        bin.install "logvalet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/logvalet/releases/download/v0.19.0/logvalet_0.19.0_Linux_x86_64.tar.gz"
      sha256 "ef7b32efa0770daa24af1322ef98906817e240e463c4282fb34940e99ea77406"
      define_method(:install) do
        bin.install "logvalet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/logvalet/releases/download/v0.19.0/logvalet_0.19.0_Linux_arm64.tar.gz"
      sha256 "3525b4c3045dd7917d481fec8bc72c3516ddcd15814311c033fa5f70ef84e40c"
      define_method(:install) do
        bin.install "logvalet"
      end
    end
  end

  test do
    system "#{bin}/logvalet", "--help"
  end
end
