# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Logvalet < Formula
  desc "LLM-first Backlog CLI with digest-oriented output"
  homepage "https://github.com/youyo/logvalet"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/youyo/logvalet/releases/download/v0.4.1/logvalet_0.4.1_Darwin_x86_64.tar.gz"
      sha256 "c79f3414147cbefa2bfb21a0e288ebd3c129c57e62d7fb312016d6234a4e2b7c"

      define_method(:install) do
        bin.install "logvalet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/youyo/logvalet/releases/download/v0.4.1/logvalet_0.4.1_Darwin_arm64.tar.gz"
      sha256 "b9171242a5f5b2eb5ab2063bbe12d1e66b516989df9deaba064713c9e6957d7d"

      define_method(:install) do
        bin.install "logvalet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/logvalet/releases/download/v0.4.1/logvalet_0.4.1_Linux_x86_64.tar.gz"
      sha256 "c5edf088f8bb81414f40f1944fd69eb6dd278b83190a13296e9d2b8792c1ae6e"
      define_method(:install) do
        bin.install "logvalet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/logvalet/releases/download/v0.4.1/logvalet_0.4.1_Linux_arm64.tar.gz"
      sha256 "af56bc1cf6a4c257919eb07fab3b869f38f867eea213e16305a9213a31333049"
      define_method(:install) do
        bin.install "logvalet"
      end
    end
  end

  test do
    system "#{bin}/logvalet", "--help"
  end
end
