# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Memoria < Formula
  desc "Claude Code 向けプロジェクト認識型ローカル RAG メモリシステム"
  homepage "https://github.com/youyo/memoria"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/youyo/memoria/releases/download/v0.1.1/memoria_0.1.1_darwin_amd64.tar.gz"
      sha256 "7598bf356fcd493f37e5c4226603fd0bda668b371b430a402adda0d30cace07f"

      define_method(:install) do
        bin.install "memoria"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/youyo/memoria/releases/download/v0.1.1/memoria_0.1.1_darwin_arm64.tar.gz"
      sha256 "03fd173fdf94725b76b2baf687f03c9c95f1eb056e9c5372a2dffe9ed1f44b32"

      define_method(:install) do
        bin.install "memoria"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/memoria/releases/download/v0.1.1/memoria_0.1.1_linux_amd64.tar.gz"
      sha256 "56b0c00320ebd0e6dbf74f533266bf7f20a55e6642dfc0ac55c05b2ed141c072"
      define_method(:install) do
        bin.install "memoria"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/memoria/releases/download/v0.1.1/memoria_0.1.1_linux_arm64.tar.gz"
      sha256 "ae48d1a14ea3be9250ee93b07f522b8aa5f5d3573e36947e3cc723e503d24666"
      define_method(:install) do
        bin.install "memoria"
      end
    end
  end

  test do
    system "#{bin}/memoria version"
  end
end
