# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Memoria < Formula
  desc "Claude Code 向けプロジェクト認識型ローカル RAG メモリシステム"
  homepage "https://github.com/youyo/memoria"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/youyo/memoria/releases/download/v0.1.5/memoria_0.1.5_darwin_amd64.tar.gz"
      sha256 "a513b1189506823a08b4da7741c3558d17f718ecaa05588d0eb5ba4f97e63273"

      define_method(:install) do
        bin.install "memoria"
        (libexec/"python").install Dir["python/*"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/youyo/memoria/releases/download/v0.1.5/memoria_0.1.5_darwin_arm64.tar.gz"
      sha256 "8cc55724aba5a97965c13bb2d9e59541f4d6764906210c0213219c3e19f68d2b"

      define_method(:install) do
        bin.install "memoria"
        (libexec/"python").install Dir["python/*"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/memoria/releases/download/v0.1.5/memoria_0.1.5_linux_amd64.tar.gz"
      sha256 "829dad06bbbc00142103307604cb26e391803920888c14a7c73d9a493c85f69d"
      define_method(:install) do
        bin.install "memoria"
        (libexec/"python").install Dir["python/*"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/memoria/releases/download/v0.1.5/memoria_0.1.5_linux_arm64.tar.gz"
      sha256 "807b18360eb2893ae47b093ebf486acf55ae312f13cb23820bd6fff7b0037cda"
      define_method(:install) do
        bin.install "memoria"
        (libexec/"python").install Dir["python/*"]
      end
    end
  end

  test do
    system "#{bin}/memoria version"
  end
end
