# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Memoria < Formula
  desc "Claude Code 向けプロジェクト認識型ローカル RAG メモリシステム"
  homepage "https://github.com/youyo/memoria"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/youyo/memoria/releases/download/v0.1.3/memoria_0.1.3_darwin_amd64.tar.gz"
      sha256 "6bfa353e7418885878862c74b2290543ad4ff2f62fabee1afda4e05fa8759430"

      define_method(:install) do
        bin.install "memoria"
        (libexec/"python").install Dir["python/*"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/youyo/memoria/releases/download/v0.1.3/memoria_0.1.3_darwin_arm64.tar.gz"
      sha256 "42c727123f86dcd8cf11f89abbc6b3fc028f98c93b9d97dc93154b39a7c246fd"

      define_method(:install) do
        bin.install "memoria"
        (libexec/"python").install Dir["python/*"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/memoria/releases/download/v0.1.3/memoria_0.1.3_linux_amd64.tar.gz"
      sha256 "44876c22d23174274c3afcbaf4e3697a82d401e2d52e56c363e8458ffba2483e"
      define_method(:install) do
        bin.install "memoria"
        (libexec/"python").install Dir["python/*"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/memoria/releases/download/v0.1.3/memoria_0.1.3_linux_arm64.tar.gz"
      sha256 "88d1f89515f76abc9dfc8bb030ac39fee472544b741721746c498eab48f91ebc"
      define_method(:install) do
        bin.install "memoria"
        (libexec/"python").install Dir["python/*"]
      end
    end
  end

  test do
    system "#{bin}/memoria version"
  end
end
