# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Passgen < Formula
  desc "Simple and secure password generator CLI tool"
  homepage "https://github.com/youyo/passgen"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/youyo/passgen/releases/download/v0.1.2/passgen_0.1.2_darwin_amd64.zip"
      sha256 "b84bbcb3f51ce0deb2e1023851a8c47b9b928f6b022fb0d7a997d895436d9ab3"

      define_method(:install) do
        bin.install "passgen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/youyo/passgen/releases/download/v0.1.2/passgen_0.1.2_darwin_arm64.zip"
      sha256 "9700378278ea1040a5037da2116572dbc75bd0d8a6abbdc0404a62f203f054d7"

      define_method(:install) do
        bin.install "passgen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/passgen/releases/download/v0.1.2/passgen_0.1.2_linux_amd64.tar.gz"
      sha256 "0f9539cf2877dc1d7391c48b3d2ed44451e9fc7e94843e3af3bccfbe63ff0a62"
      define_method(:install) do
        bin.install "passgen"
      end
    end
  end
end
