# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Passgen < Formula
  desc "Simple and secure password generator CLI tool"
  homepage "https://github.com/youyo/passgen"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/youyo/passgen/releases/download/v0.1.0/passgen_0.1.0_darwin_amd64.zip"
      sha256 "d50a18167a3b9d4bbda6862629226a6e45452c7cc7f3a9c45b8ae2724ee24241"

      define_method(:install) do
        bin.install "passgen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/youyo/passgen/releases/download/v0.1.0/passgen_0.1.0_darwin_arm64.zip"
      sha256 "9b4ac1d48c7fe669105067fb8fac51ac0cd9fdcf4f7243db831f92cdd15a0468"

      define_method(:install) do
        bin.install "passgen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/passgen/releases/download/v0.1.0/passgen_0.1.0_linux_amd64.tar.gz"
      sha256 "b4c4da6da89ee78aa6e782529bc634d4b4dbac4d2f4eb8fa77f8a8f80bae5cea"
      define_method(:install) do
        bin.install "passgen"
      end
    end
  end
end
