# This file was generated by GoReleaser. DO NOT EDIT.
class Tfstore < Formula
  desc "Login to the AWS management console."
  homepage "https://github.com/youyo/tfstore"
  version "0.0.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/youyo/tfstore/releases/download/v0.0.4/tfstore_0.0.4_Darwin_x86_64.tar.gz"
    sha256 "a32596cdcc6a614377faae75b612246af6f0d2bb2f126c7470fb011bab33c9d3"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/youyo/tfstore/releases/download/v0.0.4/tfstore_0.0.4_Linux_x86_64.tar.gz"
      sha256 "0f089690cd468bb3a6c23dc399e0c8e9e253ca6a54aeacb65b944e75863aba12"
    end
  end

  def install
    bin.install "tfstore"
    zsh_completion.install '_tfstore'
  end

  test do
    system "#{bin}/tfstore --version"
  end
end
