# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfstore < Formula
  desc "Create a Terraform remote-state backend (S3, native locking)."
  homepage "https://github.com/youyo/tfstore"
  version "1.0.2"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/youyo/tfstore/releases/download/v1.0.2/tfstore_1.0.2_darwin_arm64.tar.gz"
    sha256 "650cca98e20f22e48004ae0f87bf96afd29456a8f4be0fdeca996b43b89e5f9f"

    define_method(:install) do
      bin.install "tfstore"
      zsh_completion.install "completions/_tfstore"
    end
  end
end
