# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class X < Formula
  desc "X (Twitter) API CLI and Remote MCP server"
  homepage "https://github.com/youyo/x"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/youyo/x/releases/download/v0.4.1/x_0.4.1_Darwin_x86_64.tar.gz"
      sha256 "f2ff3cd5f0db158431cc14679c5c79c2b46519013788197879d75ee465dbb699"

      define_method(:install) do
        bin.install "x"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/youyo/x/releases/download/v0.4.1/x_0.4.1_Darwin_arm64.tar.gz"
      sha256 "f62418840fd07e4142849f776f8bbf80f47152f2b5f4981e9d9672afd0358188"

      define_method(:install) do
        bin.install "x"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/x/releases/download/v0.4.1/x_0.4.1_Linux_x86_64.tar.gz"
      sha256 "f5af7ec6ffe6ab4d9f6b681e7534656767111be05ff5df7c70b8e48a9627c47a"
      define_method(:install) do
        bin.install "x"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/x/releases/download/v0.4.1/x_0.4.1_Linux_arm64.tar.gz"
      sha256 "451558d4ea52affafd3987e469650a67c9ae021559d8dac01eefa7b6fa1b5b3b"
      define_method(:install) do
        bin.install "x"
      end
    end
  end

  test do
    system "#{bin}/x", "version"
  end
end
