# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class X < Formula
  desc "X (Twitter) API CLI and Remote MCP server"
  homepage "https://github.com/youyo/x"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/youyo/x/releases/download/v0.3.0/x_0.3.0_Darwin_x86_64.tar.gz"
      sha256 "06a1be1b97d7bd8891c65b236fbb422a69f5dc423eb09788a883d7ee77d43838"

      define_method(:install) do
        bin.install "x"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/youyo/x/releases/download/v0.3.0/x_0.3.0_Darwin_arm64.tar.gz"
      sha256 "1bd5251284bd7e84c2d50ba8c362f1746098af66ae75a74ac9538e87204fe9a5"

      define_method(:install) do
        bin.install "x"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/x/releases/download/v0.3.0/x_0.3.0_Linux_x86_64.tar.gz"
      sha256 "d0e6c340624ece630ca3d03fb51a8c271f48b08c193971c3866417b530823ac3"
      define_method(:install) do
        bin.install "x"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/youyo/x/releases/download/v0.3.0/x_0.3.0_Linux_arm64.tar.gz"
      sha256 "95b43eb1ed82d39c3c335ed1ffd818eb5a2d8f393f8aa1591404891e647d3d98"
      define_method(:install) do
        bin.install "x"
      end
    end
  end

  test do
    system "#{bin}/x", "version"
  end
end
